In [14]:
#mengimport library
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
%matplotlib inline

In [20]:
#mengambil data csv
df=pd.read_csv('F:\E-Learning\Python\Week4\dataispujkt2017.csv')
label = {'BAIK':3,
         'SEDANG':2,
         'TIDAK SEHAT':1
        }
df['kategori'].replace(label, inplace=True)
df

pm10   so2    co    o3   no2  kategori
0     63.0  34.0  25.0  21.0   2.0         2
1     16.0  32.0  16.0  19.0   1.0         3
2     18.0  32.0  17.0  20.0   2.0         3
3     24.0  32.0  22.0  20.0   2.0         3
4     29.0  32.0  25.0  14.0   2.0         3
...    ...   ...   ...   ...   ...       ...
1796  21.0  21.0  26.0  30.0   4.0         3
1797  29.0  23.0  26.0  46.0   5.0         3
1798  55.0  28.0  38.0  47.0  10.0         2
1799  51.0  26.0  31.0  49.0   8.0         2
1800  52.0  23.0  40.0  33.0   8.0         2

[1801 rows x 6 columns]

In [21]:
#Mengisi data blank dengan data rata-rata
rata_pm10 = df['pm10'].mean()
rata_so2 = df['so2'].mean()
rata_co = df['co'].mean()
rata_o3 = df['o3'].mean()
rata_no2 = df['no2'].mean()

df['pm10'] = df['pm10'].fillna(rata_pm10)
df['so2'] = df['so2'].fillna(rata_so2)
df['co'] = df['co'].fillna(rata_co)
df['o3'] = df['o3'].fillna(rata_o3)
df['no2'] = df['no2'].fillna(rata_no2)

df.isna().sum()

pm10        0
so2         0
co          0
o3          0
no2         0
kategori    0
dtype: int64

In [22]:
# Menampilkan fitur dataset
df.columns

Index(['pm10', 'so2', 'co', 'o3', 'no2', 'kategori'], dtype='object')

In [23]:
# Mengkonvert dataframe Pandas ke array Numpy
X = df[['pm10', 'so2', 'co', 'o3', 'no2']] .values  #.astype(float)
X[0:5]

array([[63., 34., 25., 21.,  2.],
       [16., 32., 16., 19.,  1.],
       [18., 32., 17., 20.,  2.],
       [24., 32., 22., 20.,  2.],
       [29., 32., 25., 14.,  2.]])

In [24]:
# Menampilkan label 5 data
y = df['kategori'].values
y[0:5]

array([2, 3, 3, 3, 3], dtype=int64)

In [25]:
# Normalisasi data
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[ 0.80333522,  0.59688342,  0.49860827, -1.41728926, -1.33268176],
       [-1.68348165,  0.44890755, -0.27818964, -1.48436447, -1.52666296],
       [-1.57765966,  0.44890755, -0.19187876, -1.45082687, -1.33268176],
       [-1.26019368,  0.44890755,  0.23967564, -1.45082687, -1.33268176],
       [-0.99563869,  0.44890755,  0.49860827, -1.6520525 , -1.33268176]])

In [26]:
# Membagi data latih dan data uji
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (1440, 5) (1440,)
Test set: (361, 5) (361,)


In [27]:
# Import library KNN
from sklearn.neighbors import KNeighborsClassifier

In [138]:
# Training
k = 1
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(n_neighbors=1)

In [130]:
# Predicting
yhat = neigh.predict(X_test)
yhat[0:361]

array([2, 2, 2, 3, 2, 1, 2, 2, 2, 2, 2, 3, 2, 2, 3, 3, 2, 3, 2, 3, 2, 2,
       3, 2, 2, 2, 3, 2, 1, 2, 2, 2, 2, 3, 2, 2, 3, 1, 2, 2, 2, 2, 3, 3,
       3, 2, 2, 2, 2, 1, 2, 2, 1, 3, 2, 3, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2,
       3, 2, 3, 1, 2, 2, 3, 3, 2, 2, 1, 2, 2, 3, 2, 1, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 3, 2, 2, 3, 2, 2, 3, 3, 2, 3, 2, 2,
       2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 1, 2, 2, 2, 2, 2, 2,
       3, 2, 2, 2, 2, 1, 2, 2, 1, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3,
       3, 2, 2, 2, 3, 2, 3, 3, 1, 2, 2, 2, 2, 2, 1, 2, 3, 2, 2, 2, 2, 2,
       3, 3, 2, 2, 2, 2, 2, 2, 2, 3, 1, 1, 2, 2, 3, 2, 3, 2, 2, 2, 2, 2,
       3, 2, 2, 2, 2, 3, 2, 3, 3, 3, 2, 2, 2, 2, 3, 3, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 3, 2, 1, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3,
       2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 1,
       2, 2, 3, 2, 2, 2, 2, 3, 1, 3, 3, 2, 2, 1, 2, 3, 2, 2, 2, 2, 2, 3,
       2, 2, 2, 1, 2, 2, 3, 3, 2, 2, 3, 2, 2, 2, 2,

In [131]:
y_test

array([2, 2, 2, 3, 2, 1, 2, 2, 1, 2, 1, 3, 2, 2, 2, 3, 2, 3, 2, 3, 2, 2,
       3, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 3, 2, 2, 3, 1, 2, 2, 1, 2, 3, 3,
       3, 2, 2, 2, 2, 1, 2, 2, 1, 3, 2, 3, 1, 2, 3, 2, 1, 2, 2, 2, 1, 2,
       3, 2, 3, 1, 2, 3, 3, 2, 2, 2, 1, 2, 2, 3, 2, 1, 2, 2, 1, 2, 3, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 2, 2, 2, 2, 3, 3, 3, 2, 3, 1, 3,
       2, 2, 3, 1, 2, 2, 2, 2, 3, 2, 3, 2, 2, 3, 2, 1, 1, 2, 2, 2, 2, 2,
       3, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2,
       3, 2, 1, 2, 3, 2, 3, 3, 2, 2, 2, 2, 2, 2, 1, 3, 3, 2, 2, 2, 2, 2,
       3, 3, 3, 3, 2, 2, 2, 2, 2, 3, 1, 1, 2, 2, 3, 2, 3, 2, 2, 2, 2, 2,
       3, 2, 2, 2, 2, 3, 2, 3, 3, 2, 2, 2, 2, 2, 3, 3, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 3, 2, 1, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3,
       2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 1, 2, 1,
       2, 2, 3, 2, 2, 2, 3, 3, 1, 3, 3, 2, 2, 1, 2, 3, 2, 2, 2, 2, 3, 3,
       3, 2, 1, 1, 2, 2, 3, 2, 2, 2, 3, 1, 2, 2, 2,

In [132]:
d_y_test=pd.DataFrame(y_test,columns=['y_test'])
d_yhat=pd.DataFrame(yhat,columns=['yhat'])
d_all=pd.merge(d_y_test,d_yhat,left_index=True,right_index=True)
d_all['dev']=yhat-y_test

jml_benar=(d_all.loc[lambda x:x['dev'] == 0,:])
akurasi=jml_benar.shape[0]/y_test.shape[0]

akurasi

0.8947368421052632

In [162]:
# menentukan K
k = X_train.shape[0]
s=np.array([0,0])
for i in range(k):
    k1=i+1
    neigh = KNeighborsClassifier(n_neighbors = k1).fit(X_train,y_train)

    # Predicting
    yhat = neigh.predict(X_test)

    d_y_test=pd.DataFrame(y_test,columns=['y_test'])
    d_yhat=pd.DataFrame(yhat,columns=['yhat'])
    d_all=pd.merge(d_y_test,d_yhat,left_index=True,right_index=True)
    d_all['dev']=yhat-y_test

    jml_benar=(d_all.loc[lambda x:x['dev'] == 0,:])
    akurasi=jml_benar.shape[0]/y_test.shape[0]
    a=np.array([k1,akurasi])
    s=np.vstack([s, a])
    #print('Nilai K:', k1, '==>> Akurasi:',akurasi)
dta=pd.DataFrame(s,columns=['k','akurasi'])
dta.loc[lambda x:x['akurasi'] == dta['akurasi'].max(),:]


k   akurasi
1  1.0  0.894737