In [1]:
# Import Library 
# Mengimpor library
import numpy as np # digunakan untuk menangani angka 
import pandas as pd # digunakan untuk menangani dataset
from sklearn.impute import SimpleImputer # digunakan untuk menangani data yang hilang
from sklearn.preprocessing import LabelEncoder, OneHotEncoder # digunakan untuk encoding data kategorikal
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split # digunakan untuk memisahkan data pelatihan dan pengujian
from sklearn.preprocessing import StandardScaler # digunakan untuk penskalaan fitur.

#Jika data dalam bentuk dataframe maka untuk mengambil setiap baris dan kolom pergunakan iloc atau loc, seperti imputer = imputer.fit (X.iloc[:, 1: ]). Tetapi, jika data dalam bentuk array tidak mempergunakan iloc atau loc

In [2]:
dataset = pd.read_csv('DataSoal.csv') # untuk mengimpor dataset ke dalam variabel
# Memisahkan atribut menjadi atribut independen dan dependen 
X = np.array(dataset.drop('Jual Online', axis=1)) # atribut untuk menentukan variabel dependen / Kelas 
Y = np.array(dataset['Jual Online']) # variabel dependen / Kelas

In [3]:
dataset.head()

Wilayah  Umur  Pemasukan Jual Online
0     Riau  49.0    86400.0          No
1     Aceh   NaN        NaN         Yes
2  Jakarta  35.0    64800.0          No
3     Aceh  43.0    73200.0          No
4  Jakarta  45.0        NaN         Yes

In [4]:
X = np.array(X)
X

array([['Riau', 49.0, 86400.0],
       ['Aceh', nan, nan],
       ['Jakarta', 35.0, 64800.0],
       ['Aceh', 43.0, 73200.0],
       ['Jakarta', 45.0, nan],
       ['Riau', 40.0, 69600.0],
       ['Aceh', nan, 62400.0],
       ['Riau', 53.0, 94800.0],
       ['Jakarta', 55.0, 99600.0],
       ['Riau', 42.0, 80400.0],
       ['Riau', 56.0, 94800.0],
       ['Jakarta', 54.0, 70600.0],
       ['Riau', 49.0, 60400.0]], dtype=object)

In [5]:
Y = np.array(Y)
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes',
       'Yes', 'No', 'Yes'], dtype=object)

In [6]:
dataset.isnull().sum()

Wilayah        0
Umur           2
Pemasukan      2
Jual Online    0
dtype: int64

In [7]:
# Penanganan Data yang Hilang
# menangani data yang hilang dan mengganti nilai yang hilang dengan nan dari numpy dan mengganti dengan median dari semua nilai lainnya 
from sklearn.impute import SimpleImputer # digunakan untuk menangani data yang hilang
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit (X[:, 1: ])
X[:, 1:] = imputer.transform (X[:, 1:])

In [8]:
X = np.array(X)
X

array([['Riau', 49.0, 86400.0],
       ['Aceh', 47.36363636363637, 77909.09090909091],
       ['Jakarta', 35.0, 64800.0],
       ['Aceh', 43.0, 73200.0],
       ['Jakarta', 45.0, 77909.09090909091],
       ['Riau', 40.0, 69600.0],
       ['Aceh', 47.36363636363637, 62400.0],
       ['Riau', 53.0, 94800.0],
       ['Jakarta', 55.0, 99600.0],
       ['Riau', 42.0, 80400.0],
       ['Riau', 56.0, 94800.0],
       ['Jakarta', 54.0, 70600.0],
       ['Riau', 49.0, 60400.0]], dtype=object)

In [9]:
# encode categorical data
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [10]:
X = np.array(X)
X

array([[2, 49.0, 86400.0],
       [0, 47.36363636363637, 77909.09090909091],
       [1, 35.0, 64800.0],
       [0, 43.0, 73200.0],
       [1, 45.0, 77909.09090909091],
       [2, 40.0, 69600.0],
       [0, 47.36363636363637, 62400.0],
       [2, 53.0, 94800.0],
       [1, 55.0, 99600.0],
       [2, 42.0, 80400.0],
       [2, 56.0, 94800.0],
       [1, 54.0, 70600.0],
       [2, 49.0, 60400.0]], dtype=object)

In [11]:
onehotencoder = OneHotEncoder()
X_category = onehotencoder.fit_transform(X[:, 0:1]).toarray()
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

In [12]:
X_category

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
Y = np.array(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1])

In [14]:
X = np.concatenate((X_category, X[:,1:]), axis=1)
X

array([[0.0, 0.0, 1.0, 49.0, 86400.0],
       [1.0, 0.0, 0.0, 47.36363636363637, 77909.09090909091],
       [0.0, 1.0, 0.0, 35.0, 64800.0],
       [1.0, 0.0, 0.0, 43.0, 73200.0],
       [0.0, 1.0, 0.0, 45.0, 77909.09090909091],
       [0.0, 0.0, 1.0, 40.0, 69600.0],
       [1.0, 0.0, 0.0, 47.36363636363637, 62400.0],
       [0.0, 0.0, 1.0, 53.0, 94800.0],
       [0.0, 1.0, 0.0, 55.0, 99600.0],
       [0.0, 0.0, 1.0, 42.0, 80400.0],
       [0.0, 0.0, 1.0, 56.0, 94800.0],
       [0.0, 1.0, 0.0, 54.0, 70600.0],
       [0.0, 0.0, 1.0, 49.0, 60400.0]], dtype=object)

In [15]:
from sklearn.model_selection import train_test_split # digunakan untuk memisahkan data pelatihan dan pengujian
# Memisahkan kumpulan data menjadi kumpulan data pelatihan dan pengujian
# splitting the dataset into training set and test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)
print('X_train =', X_train)
print('Y_train =', X_test)

X_train = [[0.0 1.0 0.0 35.0 64800.0]
 [0.0 1.0 0.0 55.0 99600.0]
 [1.0 0.0 0.0 47.36363636363637 77909.09090909091]
 [0.0 0.0 1.0 53.0 94800.0]
 [0.0 0.0 1.0 42.0 80400.0]
 [1.0 0.0 0.0 43.0 73200.0]
 [0.0 0.0 1.0 49.0 86400.0]
 [0.0 0.0 1.0 40.0 69600.0]
 [0.0 0.0 1.0 49.0 60400.0]]
Y_train = [[1.0 0.0 0.0 47.36363636363637 62400.0]
 [0.0 1.0 0.0 54.0 70600.0]
 [0.0 1.0 0.0 45.0 77909.09090909091]
 [0.0 0.0 1.0 56.0 94800.0]]


In [16]:
from sklearn.preprocessing import StandardScaler # digunakan untuk penskalaan fitur.
# Penskalaan Fitur
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [17]:
print('X_train =', X_train)
print('X_test =', X_test)

X_train = [[-0.53452248  1.87082869 -1.11803399 -1.79997153 -1.10393775]
 [-0.53452248  1.87082869 -1.11803399  1.49387655  1.68644108]
 [ 1.87082869 -0.53452248 -1.11803399  0.23622547 -0.05280759]
 [-0.53452248 -0.53452248  0.89442719  1.16449175  1.30156124]
 [-0.53452248 -0.53452248  0.89442719 -0.6471247   0.14692172]
 [ 1.87082869 -0.53452248 -1.11803399 -0.48243229 -0.43039803]
 [-0.53452248 -0.53452248  0.89442719  0.50572213  0.62802152]
 [-0.53452248 -0.53452248  0.89442719 -0.97650951 -0.71905791]
 [-0.53452248 -0.53452248  0.89442719  0.50572213 -1.45674427]]
X_test = [[ 1.87082869 -0.53452248 -1.11803399  0.23622547 -1.29637767]
 [-0.53452248  1.87082869 -1.11803399  1.32918415 -0.63887461]
 [-0.53452248  1.87082869 -1.11803399 -0.15304749 -0.05280759]
 [-0.53452248 -0.53452248  0.89442719  1.65856896  1.30156124]]
