In [ ]:
# Mengimpor perpustakaan

In [ ]:
dataset = pd. ... # untuk mengimpor dataset ke dalam variabel
# Memisahkan atribut menjadi atribut independen dan dependen 
X = ... # atribut untuk menentukan variabel dependen / Kelas 
Y = ... # variabel dependen / Kelas

In [ ]:
dataset.head()

Wilayah  Umur  Pemasukan Jual Online
0     Riau  49.0    86400.0          No
1     Aceh   NaN        NaN         Yes
2  Jakarta  35.0    64800.0          No
3     Aceh  43.0    73200.0          No
4  Jakarta  45.0        NaN         Yes

In [ ]:
X

array([['Riau', 49.0, 86400.0],
       ['Aceh', nan, nan],
       ['Jakarta', 35.0, 64800.0],
       ['Aceh', 43.0, 73200.0],
       ['Jakarta', 45.0, nan],
       ['Riau', 40.0, 69600.0],
       ['Aceh', nan, 62400.0],
       ['Riau', 53.0, 94800.0],
       ['Jakarta', 55.0, 99600.0],
       ['Riau', 42.0, 80400.0],
       ['Riau', 56.0, 94800.0],
       ['Jakarta', 54.0, 70600.0],
       ['Riau', 49.0, 60400.0]], dtype=object)

In [ ]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes',
       'Yes', 'No', 'Yes'], dtype=object)

In [ ]:
# Penanganan Data yang Hilang
# menangani data yang hilang dan mengganti nilai yang hilang dengan nan dari numpy dan mengganti dengan median dari semua nilai lainnya 
imputer = ... 
imputer = ...
X [:, 1:] = imputer.transform (X [:, 1:])

In [ ]:
X

array([['Riau', 49.0, 86400.0],
       ['Aceh', 47.36363636363637, 77909.09090909091],
       ['Jakarta', 35.0, 64800.0],
       ['Aceh', 43.0, 73200.0],
       ['Jakarta', 45.0, 77909.09090909091],
       ['Riau', 40.0, 69600.0],
       ['Aceh', 47.36363636363637, 62400.0],
       ['Riau', 53.0, 94800.0],
       ['Jakarta', 55.0, 99600.0],
       ['Riau', 42.0, 80400.0],
       ['Riau', 56.0, 94800.0],
       ['Jakarta', 54.0, 70600.0],
       ['Riau', 49.0, 60400.0]], dtype=object)

In [ ]:
# encode categorical data
labelencoder_X = LabelEncoder()
X[:, 0] = ...

In [ ]:
X

array([[2, 49.0, 86400.0],
       [0, 47.36363636363637, 77909.09090909091],
       [1, 35.0, 64800.0],
       [0, 43.0, 73200.0],
       [1, 45.0, 77909.09090909091],
       [2, 40.0, 69600.0],
       [0, 47.36363636363637, 62400.0],
       [2, 53.0, 94800.0],
       [1, 55.0, 99600.0],
       [2, 42.0, 80400.0],
       [2, 56.0, 94800.0],
       [1, 54.0, 70600.0],
       [2, 49.0, 60400.0]], dtype=object)

In [ ]:
onehotencoder = OneHotEncoder()
X_category = ...
labelencoder_Y = LabelEncoder()
Y = ...

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1])

In [ ]:
X = np.concatenate((X_category, X[:,1:]), axis=1)
X

array([[0.0, 0.0, 1.0, 49.0, 86400.0],
       [1.0, 0.0, 0.0, 47.36363636363637, 77909.09090909091],
       [0.0, 1.0, 0.0, 35.0, 64800.0],
       [1.0, 0.0, 0.0, 43.0, 73200.0],
       [0.0, 1.0, 0.0, 45.0, 77909.09090909091],
       [0.0, 0.0, 1.0, 40.0, 69600.0],
       [1.0, 0.0, 0.0, 47.36363636363637, 62400.0],
       [0.0, 0.0, 1.0, 53.0, 94800.0],
       [0.0, 1.0, 0.0, 55.0, 99600.0],
       [0.0, 0.0, 1.0, 42.0, 80400.0],
       [0.0, 0.0, 1.0, 56.0, 94800.0],
       [0.0, 1.0, 0.0, 54.0, 70600.0],
       [0.0, 0.0, 1.0, 49.0, 60400.0]], dtype=object)

In [ ]:
# Memisahkan kumpulan data menjadi kumpulan data pelatihan dan pengujian
# splitting the dataset into training set and test set
X_train, X_test, Y_train, Y_test = ...(X, Y, test_size=0.3, random_state=0)
print('X_train =', X_train)
print('Y_train =', X_test)

X_train = [[0.0 1.0 0.0 35.0 64800.0]
 [0.0 1.0 0.0 55.0 99600.0]
 [1.0 0.0 0.0 47.36363636363637 77909.09090909091]
 [0.0 0.0 1.0 53.0 94800.0]
 [0.0 0.0 1.0 42.0 80400.0]
 [1.0 0.0 0.0 43.0 73200.0]
 [0.0 0.0 1.0 49.0 86400.0]
 [0.0 0.0 1.0 40.0 69600.0]
 [0.0 0.0 1.0 49.0 60400.0]]
Y_train = [[1.0 0.0 0.0 47.36363636363637 62400.0]
 [0.0 1.0 0.0 54.0 70600.0]
 [0.0 1.0 0.0 45.0 77909.09090909091]
 [0.0 0.0 1.0 56.0 94800.0]]


In [ ]:
# Penskalaan Fitur
sc_X = StandardScaler()
X_train = sc_X. ...
X_test = sc_X.transform(...)

In [ ]:
print('X_train =', X_train)
print('X_test =', X_test)

X_train = [[-0.53452248  1.87082869 -1.11803399 -1.79997153 -1.10393775]
 [-0.53452248  1.87082869 -1.11803399  1.49387655  1.68644108]
 [ 1.87082869 -0.53452248 -1.11803399  0.23622547 -0.05280759]
 [-0.53452248 -0.53452248  0.89442719  1.16449175  1.30156124]
 [-0.53452248 -0.53452248  0.89442719 -0.6471247   0.14692172]
 [ 1.87082869 -0.53452248 -1.11803399 -0.48243229 -0.43039803]
 [-0.53452248 -0.53452248  0.89442719  0.50572213  0.62802152]
 [-0.53452248 -0.53452248  0.89442719 -0.97650951 -0.71905791]
 [-0.53452248 -0.53452248  0.89442719  0.50572213 -1.45674427]]
X_test = [[ 1.87082869 -0.53452248 -1.11803399  0.23622547 -1.29637767]
 [-0.53452248  1.87082869 -1.11803399  1.32918415 -0.63887461]
 [-0.53452248  1.87082869 -1.11803399 -0.15304749 -0.05280759]
 [-0.53452248 -0.53452248  0.89442719  1.65856896  1.30156124]]
