In [28]:
# Import Library NumPy dengan alias sebagai np 
 
import numpy as np

In [31]:
# Lengkapi code untuk membuat isi array secara manual 

# array 1 dimensi dengan nilai : 9,8,2,3,4,5
nilai_1 = np.array([9,8,2,3,4,5])  

# array 2 dimensi dengan nilai : 1,2,2,1,2,1 & 9,8,9,8,9,1
nilai_2 = np.array ([[1,2,2,1,2,1],[9,8,9,8,9,1]]) 

# array 3 dimensi dengan nilai : 1,2,2,1,2,1 & 9,8,9,8,9,1 & 0,1,3,4,5,6
nilai_3 = np.array ([[[1,2,2,1,2,1],[9,8,9,8,9,1],[0,1,3,4,5,6]]]) 


In [32]:
# cetak isi array : 
print("Expected Result")

print("isi array nilai_1:", nilai_1 , sep='\n')
print("------------------------")
print("isi array nilai_2:", nilai_2 , sep='\n') 
print("------------------------")
print("isi array nilai_3:", nilai_3 , sep='\n')

Expected Result
isi array nilai_1:
[9 8 2 3 4 5]
------------------------
isi array nilai_2:
[[1 2 2 1 2 1]
 [9 8 9 8 9 1]]
------------------------
isi array nilai_3:
[[[1 2 2 1 2 1]
  [9 8 9 8 9 1]
  [0 1 3 4 5 6]]]


In [33]:
# Lengkapi code untuk membuat isi array secara random 

np.random.seed(0)

# array 1 dimensi dengan nilai random : rentang nilai 0 sampai 100 dengan jumlah elemen 20
nilai_4 = np.random.randint(100, size=20) 

# array 2 dimensi dengan nilai random : rentang nilai :50 dgn dimensi ordo 4 X 4
nilai_5 = np.random.randint(50, size=(4,4))

# array 3 dimensi dengan nilai random : rentang nilai :50 dgn dimensi ratio 2 X 4 X 6
nilai_6 = np.random.randint(50, size=(2,4,6)) 


In [34]:
# Cetak isi array : 
print("Expected Result")

print("isi array nilai_4:", nilai_4, sep='\n')
print("--------------------------------------------------------------")
print("isi array nilai_5:", nilai_5, sep='\n') 
print("--------------------------------------------------------------")
print("isi array nilai_6:", nilai_6, sep='\n')

Expected Result
isi array nilai_4:
[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
--------------------------------------------------------------
isi array nilai_5:
[[17 37 25 13]
 [ 8  9 20 16]
 [ 5 15 47  0]
 [18 35 24 49]]
--------------------------------------------------------------
isi array nilai_6:
[[[29 19 19 14 39 32]
  [ 1  9 32 31 10 23]
  [35 11 28 34  0  0]
  [36  5 38 40 17 15]]

 [[ 4 41 42 31  1  1]
  [39 41 35 38 11 46]
  [18 27  0 14 35 12]
  [42 20 11  4  6  4]]]


In [35]:
# Lakukan cek ukuran dimensi setiap array 

print("Expected Result")
print("ukuran dimensi nilai_1:", nilai_1.ndim)
print("ukuran dimensi nilai_2:", nilai_2.ndim)
print("ukuran dimensi nilai_3:", nilai_3.ndim)
print("ukuran dimensi nilai_4:", nilai_4.ndim)
print("ukuran dimensi nilai_5:", nilai_5.ndim)
print("ukuran dimensi nilai_6:", nilai_6.ndim)

Expected Result
ukuran dimensi nilai_1: 1
ukuran dimensi nilai_2: 2
ukuran dimensi nilai_3: 3
ukuran dimensi nilai_4: 1
ukuran dimensi nilai_5: 2
ukuran dimensi nilai_6: 3


In [37]:
# Lakukan akses pada elemen data dengan kriteria indexing berikut: 

print("Expected Result")

# Lengkapi code indexing pada data array 1 
print("Elemen ke 1 pada nilai_1 :",  nilai_1[0])
print("Elemen ke 4 pada nilai_1 :",  nilai_1[5])
print("Elemen ke 9 pada nilai_1 :",  nilai_1[3])

# Lengkapi code indexing pada data array 2 
print("Elemen ke baris 2 kolom 4 pada nilai_2 :",  nilai_2[1,3])
print("Elemen ke baris 2 kolom 4 pada nilai_2 :",  nilai_2[1,3])

# Lengkapi code indexing pada data array 3
print("Elemen ke baris 1 kolom 2 pada nilai_3 :",  nilai_3[0,1,1])
print("Elemen ke baris 1 kolom 2 pada nilai_3 :",  nilai_3[0,2,1])


Expected Result
Elemen ke 1 pada nilai_1 : 9
Elemen ke 4 pada nilai_1 : 5
Elemen ke 9 pada nilai_1 : 3
Elemen ke baris 2 kolom 4 pada nilai_2 : 8
Elemen ke baris 2 kolom 4 pada nilai_2 : 8
Elemen ke baris 1 kolom 2 pada nilai_3 : 8
Elemen ke baris 1 kolom 2 pada nilai_3 : 1


In [39]:
# Lakukan proses join array
print("Expected Result")

# 1. Lengkapi code join dengan fungsi np.concate pada nilai_1 dengan menambahkan array nilai_baru = [2,3,4,5,6,6]
nilai_baru = np.array([2,3,4,5,6,6])

# Mendefinisikan fungsi np.concatenate
array_baru = np.concatenate((nilai_1,nilai_baru))

# cetak array baru
array_baru

# 2. lengkapi code join dengan fungsi np.vstack dan np.hstack pada nilai_x2 dengan menambahkan array nilai_baru1 = ([[5,5,5,5,5,6], [6,6,6,6,6,6]])

nilai_baru1 = ([[5,5,5,5,5,6], [6,6,6,6,6,6]])

# Mendefinisikan fungsi np.vstack
array_vstack = np.vstack([nilai_2, nilai_baru1])
print("Hasil join dengan vstack adalah :", array_vstack ,sep='\n')

# Mendefinisikan fungsi 2 np.hstack
array_hstack = np.hstack([nilai_2, nilai_baru1])
print("Hasil join dengan hstack adalah: ", array_hstack ,sep='\n')

print("--------------------------------------------------------------")

# 3. Lakukan join dengan fungsi np.vstack dan np.hstack pada nilai_x2 dengan menambahkan array nilai_baru2 = ([[[5,5,5,5,5,6], [6,6,6,6,6,6], [1,2,2,3,3,3]]])
nilai_baru2 = ([[[5,5,5,5,5,6], [6,6,6,6,6,6], [1,2,2,3,3,3]]])

# Mendefinisikan fungsi np.stack
array_vstack = np.vstack([nilai_3 , nilai_baru2])
print("Hasil join dengan vstack adalah :", array_vstack , sep='\n')

# Mendefinisikan fungsi np.hstack
array_hstack = np.hstack ([nilai_3, nilai_baru2 ])
print("Hasil join dengan hstack adalah: ", array_hstack ,sep='\n')




Expected Result
Hasil join dengan vstack adalah :
[[1 2 2 1 2 1]
 [9 8 9 8 9 1]
 [5 5 5 5 5 6]
 [6 6 6 6 6 6]]
Hasil join dengan hstack adalah: 
[[1 2 2 1 2 1 5 5 5 5 5 6]
 [9 8 9 8 9 1 6 6 6 6 6 6]]
--------------------------------------------------------------
Hasil join dengan vstack adalah :
[[[1 2 2 1 2 1]
  [9 8 9 8 9 1]
  [0 1 3 4 5 6]]

 [[5 5 5 5 5 6]
  [6 6 6 6 6 6]
  [1 2 2 3 3 3]]]
Hasil join dengan hstack adalah: 
[[[1 2 2 1 2 1]
  [9 8 9 8 9 1]
  [0 1 3 4 5 6]
  [5 5 5 5 5 6]
  [6 6 6 6 6 6]
  [1 2 2 3 3 3]]]


In [40]:
# Lengkapi code untuk membuat isi array dengan rentang nilai 0-25 dengan ukuran dimensi 5x5
print("Expected Result")
grid = np.arange(25).reshape((5,5))
grid


Expected Result


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
# Lengkapi code untuk split data dengan fungsi np.vsplit dan np.hsplit

# Data digunakan : grid (cek diatas)
# Mendefinisikan fungsi np.vsplit untuk melihat data atas dan data bawah dimana pada data atas terdiri atas 3 baris dan data bawah 1 baris 
data_atas, data_bawah = np.vsplit (grid, [3])
print("Hasil split data atas:", data_atas ,sep='\n')
print(" Hasil split data bawah:", data_bawah ,sep='\n') 

# Mendefinisikan fungsi np.vsplit untuk melihat data kanan dan data kiri dimana pada data kiri terdiri atas 4 kolom dan data kanan 1 kolom 
data_kiri, data_kanan = np.hsplit(grid, [4])
print("Hasil split data kiri:",data_kiri, sep='\n')
print("Hasil split data kanan:",data_kanan, sep='\n') 

Hasil split data atas:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
 Hasil split data bawah:
[[15 16 17 18 19]
 [20 21 22 23 24]]
Hasil split data kiri:
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]]
Hasil split data kanan:
[[ 4]
 [ 9]
 [14]
 [19]
 [24]]


In [47]:
# Agregasi

print("Expected Result")

# Lengkapi code untuk menentukan sum, min & max, mean dan std devisasi pada data "grid"
print('Sum : ', np.sum(grid))
print('Min : ', np.min(grid))
print('Max : ', np.max(grid))
print('Mean : ', np.mean(grid))
print('Std Deviasi : ', np.std(grid))

Expected Result
Sum :  300
Min :  0
Max :  24
Mean :  12.0
Std Deviasi :  7.211102550927978


In [48]:
# Lengkapi kode untuk proses komputasi aritmatika 
x = np.array([[1,2,4,6,8],[3,4,6,8,9]])
y = np.array([[5,6,8,9,10],[7,8,4,7,9]])
v = np.array([[9,10,2,2,2],[1,2,3,4,5],[1,1,1,1,1]])
w = np.array([[11,12,1,1,1],[2,2,2,1,8],[1,8,7,4,2]])

In [49]:
# Perkalian
print("Expected Result")

np.multiply(x,y)

Expected Result


array([[ 5, 12, 32, 54, 80],
       [21, 32, 24, 56, 81]])

In [50]:
# Pembagian
print("Expected Result")

np.divide(x,y)

Expected Result


array([[0.2       , 0.33333333, 0.5       , 0.66666667, 0.8       ],
       [0.42857143, 0.5       , 1.5       , 1.14285714, 1.        ]])

In [51]:
# Pengurangan
print("Expected Result")

np.subtract(v, w)

Expected Result


array([[-2, -2,  1,  1,  1],
       [-1,  0,  1,  3, -3],
       [ 0, -7, -6, -3, -1]])

In [52]:
# Penambahan
print("Expected Result")

np.add(w,v)

Expected Result


array([[20, 22,  3,  3,  3],
       [ 3,  4,  5,  5, 13],
       [ 2,  9,  8,  5,  3]])

In [56]:
# Squar-root (akar)
print("Expected Result")

np.sqrt(x)

Expected Result


array([[1.        , 1.41421356, 2.        , 2.44948974, 2.82842712],
       [1.73205081, 2.        , 2.44948974, 2.82842712, 3.        ]])

In [61]:
# Kuadrat
print("Expected Result")

np.power(x,2)

Expected Result


array([[ 1,  4, 16, 36, 64],
       [ 9, 16, 36, 64, 81]], dtype=int32)